#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { randomBytes, pbkdf2Sync, createCipheriv, createDecipheriv, createHash } from "node:crypto";
import { basename, extname } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
const CHUNK=1024*1024,HEADER=36,MAGIC=Buffer.from("ECV2"),ITER=250000;
function prompt(){const rl=createInterface({input,output});return rl.question("Password: ").finally(()=>rl.close());}
const key=(p,s)=>pbkdf2Sync(p,s,ITER,32,"sha256");
const aad=(h,i)=>{const a=Buffer.alloc(40);h.copy(a);a.writeUInt32LE(i,36);return a;};
const header=(s,n,c)=>{const h=Buffer.alloc(HEADER);MAGIC.copy(h);s.copy(h,4);h.writeUInt32LE(CHUNK,20);h.writeBigUInt64LE(BigInt(n),24);h.writeUInt32LE(c,32);return h;};
function encrypt(d,p){const s=randomBytes(16),c=Math.ceil(d.length/CHUNK),h=header(s,d.length,c),k=key(p,s),parts=[h];for(let i=0,o=0;o<d.length;i++,o+=CHUNK){const x=d.subarray(o,Math.min(o+CHUNK,d.length)),iv=randomBytes(12),e=createCipheriv("aes-256-gcm",k,iv);e.setAAD(aad(h,i));const ct=Buffer.concat([e.update(x),e.final(),e.getAuthTag()]);const seg=Buffer.alloc(16+ct.length);iv.copy(seg);seg.writeUInt32LE(ct.length,12);ct.copy(seg,16);parts.push(seg);}return Buffer.concat(parts);}
function decrypt(d,p){if(d.length<HEADER||!d.subarray(0,4).equals(MAGIC))throw Error("Unsupported or invalid ECV2 file");const s=d.subarray(4,20),cs=d.readUInt32LE(20),size=Number(d.readBigUInt64LE(24)),count=d.readUInt32LE(32);if(cs!==CHUNK||count!==Math.ceil(size/CHUNK))throw Error("Invalid ECV2 header");const h=d.subarray(0,HEADER),k=key(p,s),parts=[];let o=HEADER,total=0;for(let i=0;i<count;i++){if(o+16>d.length)throw Error("Truncated ciphertext");const iv=d.subarray(o,o+12),len=d.readUInt32LE(o+12);o+=16;if(len<16||o+len>d.length)throw Error("Invalid ciphertext chunk");const ct=d.subarray(o,o+len);o+=len;const dec=createDecipheriv("aes-256-gcm",k,iv);dec.setAAD(aad(h,i));dec.setAuthTag(ct.subarray(-16));const pt=Buffer.concat([dec.update(ct.subarray(0,-16)),dec.final()]);if(i<count-1&&pt.length!==CHUNK)throw Error("Invalid chunk size");parts.push(pt);total+=pt.length;}if(o!==d.length||total!==size)throw Error("Corrupted or incomplete ciphertext");return Buffer.concat(parts);}
function usage(){console.log("Encryption Center CLI\n\n  encryption-center encrypt <input> [output]\n  encryption-center decrypt <input.ecv> [output]\n  encryption-center hash <input> [sha256|sha512]\n  encryption-center inspect <input.ecv>");}
const [cmd,inputPath,outputPath]=process.argv.slice(2);if(!cmd||cmd==="help"||cmd==="--help"){usage();process.exit(0);}try{if(!inputPath)throw Error("Input file required");const data=await readFile(inputPath);if(cmd==="hash"){const alg=(outputPath||"sha256").replace("-","").toLowerCase();console.log(`${alg}: ${createHash(alg).update(data).digest("hex")}`);process.exit(0);}if(cmd==="inspect"){if(!data.subarray(0,4).equals(MAGIC))throw Error("Not an ECV2 file");console.log(JSON.stringify({format:"ECV2",algorithm:"AES-256-GCM",kdf:"PBKDF2-SHA-256",iterations:ITER,chunkSize:CHUNK,bytes:data.length,plaintextBytes:Number(data.readBigUInt64LE(24)),chunks:data.readUInt32LE(32)},null,2));process.exit(0);}const p=await prompt();if(!p)throw Error("Password cannot be empty");if(cmd==="encrypt"){await writeFile(outputPath||`${inputPath}.enc`,encrypt(data,p));console.log("Encrypted successfully.");}else if(cmd==="decrypt"){await writeFile(outputPath||basename(inputPath,extname(inputPath)),decrypt(data,p));console.log("Decrypted successfully.");}else usage();}catch(e){console.error(`Error: ${e.message}`);process.exit(1);}
