import React, { useMemo, useState } from "react";
import { Calculator, Gauge, KeyRound, FileDigit } from "lucide-react";
import PageHeader, { SecurityNote } from "@/components/PageHeader";
import SecurityBadge from "@/components/SecurityBadge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { estimateStrength } from "@/lib/crypto/passwords";
import { useI18n } from "@/lib/i18n";

const profiles = [
  ["Fast", "PBKDF2-SHA-256", "100,000", "Lower interactive delay; weaker work factor."],
  ["Balanced", "PBKDF2-SHA-256", "250,000", "Encryption Center's default ECV2 profile."],
  ["Memory-hard", "Argon2id", "64 MiB / 3 iterations", "Designed to make large-scale password guessing more expensive."],
];
export default function SecurityCalculator(){const {t}=useI18n();const [password,setPassword]=useState("");const [size,setSize]=useState(1024);const s=useMemo(()=>estimateStrength(password),[password]);const overhead=Math.ceil(size/(1024*1024))*((12+4+16));return <div className="mx-auto max-w-4xl px-4 py-6 sm:px-8 sm:py-10"><PageHeader icon={Calculator} title={t("calculator.title")} subtitle={t("calculator.subtitle")}><SecurityBadge level="secure"/></PageHeader><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-border p-5"><h2 className="flex items-center gap-2 font-semibold"><Gauge className="h-5 w-5 text-red-400"/>Password analysis</h2><div className="mt-4 space-y-3"><Label>Password sample</Label><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Type a password to estimate entropy"/><div className="grid grid-cols-3 gap-2">{[["Entropy",`${s.entropy} bits`],["Score",`${s.score}/4`],["Length",password.length]].map(([k,v])=><div key={k} className="rounded-xl bg-muted/40 p-3"><div className="text-[10px] uppercase text-muted-foreground">{k}</div><div className="mt-1 font-semibold">{v}</div></div>)}</div><div className="rounded-xl border border-border p-3 text-sm"><span className="text-muted-foreground">Estimated category: </span><strong>{s.label}</strong></div><p className="text-xs leading-5 text-muted-foreground">This is an entropy-style estimate, not a prediction of real-world cracking time. Password reuse, leaks, dictionaries and attacker knowledge can change the result.</p></div></section><section className="rounded-2xl border border-border p-5"><h2 className="flex items-center gap-2 font-semibold"><FileDigit className="h-5 w-5 text-red-400"/>File overhead</h2><div className="mt-4 space-y-3"><Label>Plaintext size (bytes)</Label><Input type="number" min="0" value={size} onChange={e=>setSize(Math.max(0,Number(e.target.value)||0))}/><div className="rounded-xl bg-muted/40 p-4"><div className="text-xs text-muted-foreground">Approximate ECV2 structural overhead</div><div className="mt-1 text-2xl font-semibold">{(36+overhead).toLocaleString()} bytes</div><div className="mt-1 text-xs text-muted-foreground">Header + one 32-byte per-chunk envelope (nonce, length field, GCM tag).</div></div></div></section></div><section className="mt-5 rounded-2xl border border-border p-5"><h2 className="flex items-center gap-2 font-semibold"><KeyRound className="h-5 w-5 text-red-400"/>KDF profiles</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{profiles.map(([name,kdf,cost,desc])=><div key={name} className="rounded-xl border border-border bg-card/30 p-4"><div className="font-semibold">{name}</div><div className="mt-2 font-mono text-xs">{kdf}</div><div className="mt-1 text-xs text-muted-foreground">{cost}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">{desc}</p></div>)}</div></section><SecurityNote variant="warn">{t("calculator.note")}</SecurityNote></div>}
